inherits spelskil;

function void fill_spellbook(obj user, obj usedon) {
	loc place = getLocation(usedon);
	int x = getX(place) + 0x01;
	int y = getY(place) + 0x01;
	setX(place, x);
	setY(place, y);
	int dummy;
	obj birdi_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(birdi_scroll, "birdi");
	dummy = putObjContainer(birdi_scroll, usedon);
	obj spell_clumsy = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_clumsy, "clumsy");
	dummy = putObjContainer(spell_clumsy, usedon);
	obj creatfod_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(creatfod_scroll, "creatfod");
	dummy = putObjContainer(creatfod_scroll, usedon);
	obj spell_feeble_mind = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_feeble_mind, "feblmind");
	dummy = putObjContainer(spell_feeble_mind, usedon);
	obj scroll_heal = createGlobalObjectAt(0x0EF3, place);
	attachScript(scroll_heal, "heal");
	dummy = putObjContainer(scroll_heal, usedon);
	obj magarrow_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(magarrow_scroll, "magarrow");
	dummy = putObjContainer(magarrow_scroll, usedon);
	obj nitesite_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(nitesite_scroll, "nitesite");
	dummy = putObjContainer(nitesite_scroll, usedon);
	obj weaken_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(weaken_scroll, "weaken");
	dummy = putObjContainer(weaken_scroll, usedon);
	obj agility_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(agility_scroll, "agility");
	dummy = putObjContainer(agility_scroll, usedon);
	obj cunning_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(cunning_scroll, "cunning");
	dummy = putObjContainer(cunning_scroll, usedon);
	obj cure_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(cure_scroll, "cure");
	dummy = putObjContainer(cure_scroll, usedon);
	obj harm_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(harm_scroll, "harm");
	dummy = putObjContainer(harm_scroll, usedon);
	obj magctrap_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(magctrap_scroll, "magctrap");
	dummy = putObjContainer(magctrap_scroll, usedon);
	obj spell_mguntrap = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_mguntrap, "mguntrap");
	dummy = putObjContainer(spell_mguntrap, usedon);
	obj spell_protect = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_protect, "protect");
	dummy = putObjContainer(spell_protect, usedon);
	obj spell_strength = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_strength, "strength");
	dummy = putObjContainer(spell_strength, usedon);
	obj spell_bless = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_bless, "bless");
	dummy = putObjContainer(spell_bless, usedon);
	obj spell_fireball = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_fireball, "fireball");
	dummy = putObjContainer(spell_fireball, usedon);
	obj spell_magclock = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_magclock, "magclock");
	dummy = putObjContainer(spell_magclock, usedon);
	obj spell_poison = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_poison, "poison");
	dummy = putObjContainer(spell_poison, usedon);
	obj telkinesis_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(telkinesis_scroll, "telknsis");
	dummy = putObjContainer(telkinesis_scroll, usedon);
	obj teleport_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(teleport_scroll, "teleport");
	dummy = putObjContainer(teleport_scroll, usedon);
	obj unlock_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(unlock_scroll, "unlock");
	dummy = putObjContainer(unlock_scroll, usedon);
	obj wall_of_stone_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(wall_of_stone_scroll, "wallston");
	dummy = putObjContainer(wall_of_stone_scroll, usedon);
	obj arch_cure_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(arch_cure_scroll, "archcure");
	dummy = putObjContainer(arch_cure_scroll, usedon);
	obj arch_protection_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(arch_protection_scroll, "aprotect");
	dummy = putObjContainer(arch_protection_scroll, usedon);
	obj curse_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(curse_scroll, "curse");
	dummy = putObjContainer(curse_scroll, usedon);
	obj fire_field_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(fire_field_scroll, "firefild");
	dummy = putObjContainer(fire_field_scroll, usedon);
	obj grtheal_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(grtheal_scroll, "grtheal");
	dummy = putObjContainer(grtheal_scroll, usedon);
	obj lightng_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(lightng_scroll, "lightng");
	dummy = putObjContainer(lightng_scroll, usedon);
	obj manadran_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(manadran_scroll, "manadran");
	dummy = putObjContainer(manadran_scroll, usedon);
	obj recall_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(recall_scroll, "recall");
	dummy = putObjContainer(recall_scroll, usedon);
	obj bldsprts_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(bldsprts_scroll, "bldsprts");
	dummy = putObjContainer(bldsprts_scroll, usedon);
	obj dsplfild_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(dsplfild_scroll, "dsplfild");
	dummy = putObjContainer(dsplfild_scroll, usedon);
	obj incognto_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(incognto_scroll, "incognto");
	dummy = putObjContainer(incognto_scroll, usedon);
	obj spell_magic_reflect = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_magic_reflect, "magrflct");
	dummy = putObjContainer(spell_magic_reflect, usedon);
	obj spell_mind_blast = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_mind_blast, "mindblst");
	dummy = putObjContainer(spell_mind_blast, usedon);
	obj spell_paralyze = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_paralyze, "paralyze");
	dummy = putObjContainer(spell_paralyze, usedon);
	obj spell_poison_field = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_poison_field, "posnfild");
	dummy = putObjContainer(spell_poison_field, usedon);
	obj spell_summon_creature = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_summon_creature, "summoncr");
	dummy = putObjContainer(spell_summon_creature, usedon);
	obj spell_dispel = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_dispel, "dispel");
	dummy = putObjContainer(spell_dispel, usedon);
	obj spell_energy_bolt = createGlobalObjectAt(0x0EF3, place);
	attachScript(spell_energy_bolt, "nrgybolt");
	dummy = putObjContainer(spell_energy_bolt, usedon);
	obj scroll_explosion = createGlobalObjectAt(0x0EF3, place);
	attachScript(scroll_explosion, "exploson");
	dummy = putObjContainer(scroll_explosion, usedon);
	obj scroll_invis = createGlobalObjectAt(0x0EF3, place);
	attachScript(scroll_invis, "invis");
	dummy = putObjContainer(scroll_invis, usedon);
	obj scroll_mark = createGlobalObjectAt(0x0EF3, place);
	attachScript(scroll_mark, "mark");
	dummy = putObjContainer(scroll_mark, usedon);
	obj scroll_mass_curse = createGlobalObjectAt(0x0EF3, place);
	attachScript(scroll_mass_curse, "mascurse");
	dummy = putObjContainer(scroll_mass_curse, usedon);
	obj scroll_para_field = createGlobalObjectAt(0x0EF3, place);
	attachScript(scroll_para_field, "parafild");
	dummy = putObjContainer(scroll_para_field, usedon);
	obj scroll_reveal = createGlobalObjectAt(0x0EF3, place);
	attachScript(scroll_reveal, "reveal");
	dummy = putObjContainer(scroll_reveal, usedon);
	obj scroll_chain_lightning = createGlobalObjectAt(0x0EF3, place);
	attachScript(scroll_chain_lightning, "chainltg");
	dummy = putObjContainer(scroll_chain_lightning, usedon);
	obj nrgy_fild = createGlobalObjectAt(0x0EF3, place);
	attachScript(nrgy_fild, "nrgyfild");
	dummy = putObjContainer(nrgy_fild, usedon);
	obj flam_strk = createGlobalObjectAt(0x0EF3, place);
	attachScript(flam_strk, "flamstrk");
	dummy = putObjContainer(flam_strk, usedon);
	obj gate_trvl = createGlobalObjectAt(0x0EF3, place);
	attachScript(gate_trvl, "gatetrvl");
	dummy = putObjContainer(gate_trvl, usedon);
	obj mana_vamp = createGlobalObjectAt(0x0EF3, place);
	attachScript(mana_vamp, "manavamp");
	dummy = putObjContainer(mana_vamp, usedon);
	obj mass_dspl = createGlobalObjectAt(0x0EF3, place);
	attachScript(mass_dspl, "massdspl");
	dummy = putObjContainer(mass_dspl, usedon);
	obj meteor = createGlobalObjectAt(0x0EF3, place);
	attachScript(meteor, "meteor");
	dummy = putObjContainer(meteor, usedon);
	obj polymrph = createGlobalObjectAt(0x0EF3, place);
	attachScript(polymrph, "polymrph");
	dummy = putObjContainer(polymrph, usedon);
	obj earthquk = createGlobalObjectAt(0x0EF3, place);
	attachScript(earthquk, "earthquk");
	dummy = putObjContainer(earthquk, usedon);
	obj nrgy_vrtx_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(nrgy_vrtx_scroll, "nrgyvrtx");
	dummy = putObjContainer(nrgy_vrtx_scroll, usedon);
	obj resurect_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(resurect_scroll, "resurect");
	dummy = putObjContainer(resurect_scroll, usedon);
	obj sumaire_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(sumaire_scroll, "sumaire");
	dummy = putObjContainer(sumaire_scroll, usedon);
	obj sumdaem_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(sumdaem_scroll, "sumdaem");
	dummy = putObjContainer(sumdaem_scroll, usedon);
	obj sumearth_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(sumearth_scroll, "sumearth");
	dummy = putObjContainer(sumearth_scroll, usedon);
	obj sumfire_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(sumfire_scroll, "sumfire");
	dummy = putObjContainer(sumfire_scroll, usedon);
	obj sumh2o_scroll = createGlobalObjectAt(0x0EF3, place);
	attachScript(sumh2o_scroll, "sumh2o");
	dummy = putObjContainer(sumh2o_scroll, usedon);
	return();
}

trigger use {
	targetObj(user, this);
	return(0x00);
}

trigger targetobj {
	fill_spellbook(user, usedon);
	return(0x00);
}
